#!/bin/bash

# create a tar.gz of the release
origDir=`pwd`
tmpDir=/tmp/hnocs.$$
mkdir -p $tmpDir
D=`date +%d_%m_%g`
cpDir=$tmpDir/hnocs.$D
mkdir -p $cpDir
tarFileName=hnocs.$D.tgz

echo Releasing in $tmpDir

# get the ignored files/dirs
ignore=`svn propget -R do-not-release`

# get all the files
#find . \( -name .svn -prune \) -o \( -name "*.cc" -o -name "*.h" -o -name "*.ned" -o -name "*.msg" -o -name "pack*" \) -print > $tmpDir/files
echo Copying files ...
svn stat -v | grep -v ^\? | awk '{print $NF}' > $tmpDir/files

# filter out any of the do-not-release items
echo Filterring non distributed ...
for i in $ignore; do
   grep -v $i $tmpDir/files > $tmpDir/files.x
   mv -f $tmpDir/files.x $tmpDir/files
done
grep -v _m\. $tmpDir/files > $tmpDir/files.x
mv -f $tmpDir/files.x $tmpDir/files

# copy the files
for i in `cat $tmpDir/files`; do
   d=`dirname $i`
   mkdir -p $cpDir/$d
   if ! test -d $i; then
      cp -p $i $cpDir/$i
   fi
done

cd $tmpDir
tar cfz $tarFileName hnocs.$D

echo Building project ...
cd hnocs.$D
opp_makemake -f --deep -O out -o hnocs > /dev/null
make > /dev/null

if test $? = 0; then
   echo Built HNOCS distribution into $tarFileName
   mv ../$tarFileName $origDir
else 
   echo DIST FAILED
fi
echo Cleaning up
cd $origDir
rm -rf $tmpDir
