//
// Generated file, do not edit! Created by nedtool 4.6 from CMP.msg.
//

#ifndef _CMP_M_H_
#define _CMP_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "App_m.h"
// }}

/**
 * Enum generated from <tt>CMP.msg:29</tt> by nedtool.
 * <pre>
 * enum cmpOpType
 * {
 * 
 *     CMP_OP_READ = 1;
 *     CMP_OP_WRITE = 2;
 * }
 * </pre>
 */
enum cmpOpType {
    CMP_OP_READ = 1,
    CMP_OP_WRITE = 2
};

/**
 * Class generated from <tt>CMP.msg:33</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CMPMsg extends AppMsg
 * {
 *     int origin;     // 1=L1, 2=L2, 3=DRAM        
 *     int operation;  // CMP_OP_TYPE
 *     int l2hit;      // non zero means the L2 is hit
 *     int address;
 *     int length;     // in bytes
 *     bool roundtrip = false; // true if is a closed circle CMPMsg (request->response type) 
 * }
 * </pre>
 */
class CMPMsg : public ::AppMsg
{
  protected:
    int origin_var;
    int operation_var;
    int l2hit_var;
    int address_var;
    int length_var;
    bool roundtrip_var;

  private:
    void copy(const CMPMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CMPMsg&);

  public:
    CMPMsg(const char *name=NULL, int kind=0);
    CMPMsg(const CMPMsg& other);
    virtual ~CMPMsg();
    CMPMsg& operator=(const CMPMsg& other);
    virtual CMPMsg *dup() const {return new CMPMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getOrigin() const;
    virtual void setOrigin(int origin);
    virtual int getOperation() const;
    virtual void setOperation(int operation);
    virtual int getL2hit() const;
    virtual void setL2hit(int l2hit);
    virtual int getAddress() const;
    virtual void setAddress(int address);
    virtual int getLength() const;
    virtual void setLength(int length);
    virtual bool getRoundtrip() const;
    virtual void setRoundtrip(bool roundtrip);
};

inline void doPacking(cCommBuffer *b, CMPMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CMPMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CMP_M_H_

